auto_save=yes

#save_bind=
auto_save_skip_past=100

hide_same_dir=no
auto_run_idle=yes
write_watch_later=yes
display_bind=tab

mouse_controls=yes
mouse_drag_scrolling=yes
#dragging deadzones in percentages: top,right,bottom,left
drag_deadzone_margin=15,0,0,0

log_path=history.log
date_format=%d/%m/%y %X

show_paths=no
split_paths=no
slice_longfilenames=yes
slice_longfilenames_amount=77
slice_longfilenames_amount_uosc=120

font_size=55
font_scale=50
border_size=1.65
bold_text=yes
hi_color=FFCF46
center_list=yes
ellipsis=yes
alt_digits=yes

list_show_amount=1000
list_show_amount_dyn_menu=0
use_uosc_menu=no
double_menu_key=yes

#Create custom prefixes/highlight colors. Syntax: "patternMatchRule|prefixName|prefixColor|highlightColor". Rules are comma separated.
#Prefix and highlightColor can be used separately and turned off by using double quotes(""), color values use RRGGBB format and rule matching is path based.
custom_colors={audio}|♫|1DB954|"",^http.?://youtu.be/| ↪Youtube ▶|FF0000|"",http.?://www.youtube.com/watch| ↪Youtube ▶|FF0000|"",http.?://www.twitch.tv/(.*)videos?| ↪VoD ▶|00ADEE|57C7FF,streamlink%-twitch%-gui.exe| ↪Live ▶|9F4CEC|A970FF,^https?://?w?w?w?%.?twitch%.tv/([^/]+)/?$| ↪Live ▶|9F4CEC|A970FF
